// Generates a static fallback trophy SVG from a real, live-rendered snapshot.
// Run with a valid token available as GITHUB_TOKEN1 (e.g. your `gh auth token`,
// which has the right read scopes even though it isn't the app's normal token):
//
//   GITHUB_TOKEN1=$(gh auth token) deno run --allow-net --allow-env \
//     scripts/generate-fallback-trophy.ts
//
// Writes public/fallback-trophy.svg and src/fallbackTrophy.ts (the module the
// API actually imports). Re-run whenever you want to refresh the snapshot.

import { Card } from "../src/card.ts";
import { COLORS } from "../src/theme.ts";
import { GithubRepositoryService } from "../src/Repository/GithubRepository.ts";
import { GithubApiService } from "../src/Services/GithubApiService.ts";
import { ServiceError } from "../src/Types/index.ts";

const username = "CynthiaWahome";
const serviceProvider = new GithubApiService();
const client = new GithubRepositoryService(serviceProvider).repository;

const userInfo = await client.requestUserInfo(username);
if (userInfo instanceof ServiceError) {
  console.error("Failed to fetch real snapshot:", userInfo.message);
  Deno.exit(1);
}

const svg = new Card(
  [],
  [],
  5,
  3,
  110,
  15,
  15,
  true,
  false,
).render(userInfo, COLORS.tokyonight);

const tagged = svg.replace(
  "</svg>",
  `<!-- FALLBACK SNAPSHOT: generated ${
    new Date().toISOString().slice(0, 10)
  }, not live data --></svg>`,
);

await Deno.writeTextFile("public/fallback-trophy.svg", tagged);
await Deno.writeTextFile(
  "src/fallbackTrophy.ts",
  `// AUTO-GENERATED by scripts/generate-fallback-trophy.ts — do not hand-edit.\n` +
    `// Regenerate with: GITHUB_TOKEN1=$(gh auth token) deno run --allow-net --allow-env scripts/generate-fallback-trophy.ts\n` +
    `export const FALLBACK_TROPHY_SVG = ${JSON.stringify(tagged)};\n`,
);

console.log("Wrote public/fallback-trophy.svg and src/fallbackTrophy.ts");
